name: Convert Markdown to PDF

on:
  push:
    paths:
      - '**/*.md'  # Trigger this workflow when an .md file is pushed

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install pandoc and texlive-full
      run: sudo apt-get update && sudo apt-get install -y pandoc texlive-full

    - name: Debugging - Locate pdflatex and xelatex
      run: |
        which pdflatex
        which xelatex

    - name: Create PDF directory
      run: mkdir -p PDF

    - name: Convert Markdown to PDF
      run: |
        for mdfile in $(find . -name "*.md"); do
          filename=$(basename -- "$mdfile")
          filename_no_ext="${filename%.*}"
          pdffile="PDF/${filename_no_ext}.pdf"
          echo "Converting $mdfile to $
