name: Convert Markdown to PDF

on:
  push:
    paths:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install pandoc
      run: sudo apt-get install -y pandoc

    - name: Install pdflatex  # Option 1
      run: sudo apt-get install -y texlive  # This will install pdflatex among other things

    - name: Create PDF directory
      run: mkdir -p PDF

    - name: Convert Markdown to PDF
      run: |
        for mdfile in $(find . -name "*.md"); do
          filename=$(basename -- "$mdfile")
          filename_no_ext="${filename%.*}"
          pdffile="PDF/${filename_no_ext}.pdf"
          echo "Converting $mdfile to $pdffile"
          pandoc $mdfile --pdf-engine=xelatex -o $pdffile  # Option 2: specify xelatex as engine
        done
